.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 Julian Gilbey <jdg@debian.org>
.\"
.TH SEND2TRASH 1 "Jan 2021"
.SH NAME
send2trash \- send files to the trash
.SH SYNOPSIS
.B send2trash
.RI [ options ] " file" ...
.SH DESCRIPTION
This manual page documents the
.B send2trash
command.
.PP
\fBsend2trash\fP is a program that sends the listed files to the trash
using the operating system's conventions.  On Linux systems, the trash
is in \fB~/.local/share/Trash\fP.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-verbose
Report on deleted files to stdout.
.SH NOTES
This manual page was written for the Debian GNU/Linux distribution
(but may be used by others), because the original program does not
have a manual page.
